services:
  postgres:
    image: postgres:15
    container_name: datasheet_pg
    environment:
      POSTGRES_DB: datasheets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: varad
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
